### ISSUE TITLE
lsd not installing

### ISSUE THREAD

**Issue by sarg3nt** [innobead/huber#127]
## Describe the bug

The package `lsd` is not installing.
I've checked the generated yaml file and it looks fine.  I've even tried using my own `huber.yml` file which we use for some other apps and adding it there but still does not install. 

NOTE: When an app fails to install, i.e. there are no binaries extracted and installed, `huber` acts as if it is installed.  It should check that something got installed and if not return a non 0 exit code so automation scripts can fail as they should.

## To Reproduce

`huber install lsd`
Notice nothing is installed.

## Expected behavior

`lsd` should be installed.

## Environment

- OS version
   Linux ccdb9fb1aaa1 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Huber version
   huber v0.3.11 Commit: 9b81911-20221212170207

**Comment by JuanmaDevG** [comment]
Whenever I try to add arepository like this:

`
huber repo add neovim --url https://github.com/neovim/neovim

huber install neovim
`

I get the following error:

error: reqwest::Error { kind: Status(404), url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("raw.githubusercontent.com")), port: None, path: "/neovim/neovim/master/huber.yaml", query: None, fragment: None } }

Do I need to create a huber.yaml file that locates the release dependencies?

**Comment by innobead** [comment]
This has been resolved in https://github.com/innobead/huber/pull/130

**Comment by innobead** [comment]
> ```
> error: reqwest::Error { kind: Status(404), url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("raw.githubusercontent.com")), port: None, path: "/neovim/neovim/master/huber.yaml", query: None, fragment: None } }
> ```
> 
> Do I need to create a huber.yaml file that locates the release dependencies?

Exactly, this is the way for remote repo support in Huber.
