### ISSUE TITLE
Rancher release info not accurate

### ISSUE THREAD

**Issue by oskapt** [innobead/huber#16]
**Describe the bug**

The output of `huber search rancher --all` only shows releases up through 2.4.9. It doesn't show anything in the 2.4 line higher than that, nor does is show anything from 2.5.

**Environment**

macOS. (your template still refers to `kubefire` btw)

```
 - OS version
    - run `cat /etc/os-release`
 - Kubefire version
    - run `kubefire version`
 - Kubefire runtime info
    - run `kubefire info` 
```

**Comment by oskapt** [comment]
Sorry - my bad. It's the Rancher CLI! :)

**Comment by innobead** [comment]
NP! thanks for reporting the template issue :wink:
